DROP TABLE IF EXISTS bronze.erp_stk_order
CREATE TABLE bronze.erp_stk_order(
[company] [smallint] NOT NULL,
	[sector] [smallint] NOT NULL,
	[region] [smallint] NOT NULL,
	[branch] [int] NOT NULL,
	[section] [smallint] NOT NULL,
	[transtype] [smallint] NOT NULL,
	[doctype] [smallint] NOT NULL,
	[orderno] [int] NOT NULL,
	[orderdate] [smalldatetime] NOT NULL,
	[sites] [int] NOT NULL,
	[sites_section] [smallint] NULL,
	[reordertype] [smallint] NULL,
	[reorderno] [int] NULL,
	[reorderdate] [smalldatetime] NULL,
	[goodstype] [smallint] NOT NULL,
	[status] [smallint] NULL,
	[invoiceno] [int] NULL,
	[invoicedate] [smalldatetime] NULL,
	[examinationno] [char](8) NULL,
	[examinationdate] [smalldatetime] NULL,
	[storeorder] [char](8) NULL,
	[storedate] [smalldatetime] NULL,
	[shipmentno] [int] NULL,
	[shipmentdate] [smalldatetime] NULL,
	[review] [smallint] NULL,
	[reviewdate] [smalldatetime] NULL,
	[posting] [smallint] NULL,
	[postingdate] [smalldatetime] NULL,
	[userid] [int] NULL,
	[transid] [smallint] NULL,
	[transdate] [smalldatetime] NULL,
	[collection] [smallint] NULL,
	[new_entry] [smallint] NULL,
	[dispatch_type] [smallint] NULL,
	[purchase_flag] [smallint] NULL,
	[Fin_Entryno] [int] NULL,
	[Fin_Entrydate] [datetime] NULL,
	[Payment_type] [smallint] NULL,
	[Due_date] [datetime] NULL,
	[Return_doc_no] [int] NULL,
	[Return_doc_date] [datetime] NULL,
	[Invoice_type] [smallint] NULL,
	[Whole_seller] [int] NULL,
	[order_code] [numeric](38, 0) NULL,
	[Branch_request] [int] NULL,
	[Discountype] [smallint] NULL,
	[Discountpercentage] [decimal](12, 3) NULL,
	[Discountvalue] [decimal](12, 3) NULL,
	[Totalvalue] [decimal](12, 3) NULL,
	[Netvalue] [decimal](12, 3) NULL,
	[Finalizedby] [int] NULL,
	[Finalizeddate] [datetime] NULL,
	[Reviewedby] [int] NULL,
	[Postedby] [int] NULL,
	[Tax_add] [smallint] NULL,
	[Tax_value] [decimal](12, 3) NULL,
	[Entered_from] [smallint] NULL,
	[Entered_time] [datetime] NULL,
	[Order_item_count] [smallint] NULL,
	[Notes] [varchar](255) NULL,
	[Reasonid] [int] NULL,
	[DispatchNature] [int] NULL,
	[Pos_id] [smallint] NULL,
	[DriverCode] [int] NULL,
	[Carlicenseplatenumber] [varchar](30) NULL,
	[Penalty_code] [smallint] NULL,
	[Penalty_fees] [decimal](12, 3) NULL,
	[SuppliersInvoicesNO] [varchar](500) NULL,
	[CarlockerNO] [varchar](75) NULL,
	[Reserved1] [varchar](500) NULL,
	[Reserved2] [varchar](500) NULL,
	[Reserved3] [varchar](500) NULL,
	[Reserved4] [numeric](18, 3) NULL,
	[Reserved5] [numeric](18, 3) NULL,
	[Reserved6] [datetime] NULL,
	[Reserved7] [datetime] NULL,
	[Reserved8] [int] NULL,
	[Reserved9] [int] NULL,
	[Reserved10] [int] NULL,
	[Reserved11] [datetime] NULL,
	[Reserved12] [datetime] NULL,
	[Reserved13] [int] NULL,
	[Reserved14] [int] NULL,
	[Reserved15] [int] NULL,
 CONSTRAINT [p_order] PRIMARY KEY NONCLUSTERED 
(
	[company] ASC,
	[sector] ASC,
	[region] ASC,
	[branch] ASC,
	[section] ASC,
	[transtype] ASC,
	[doctype] ASC,
	[orderno] ASC,
	[orderdate] ASC)
)
