DROP TABLE IF EXISTS bronze.erp_stk_order_items
CREATE TABLE bronze.erp_stk_order_items(
[company] [smallint] NOT NULL,
	[sector] [smallint] NOT NULL,
	[region] [smallint] NOT NULL,
	[branch] [int] NOT NULL,
	[section] [smallint] NOT NULL,
	[transtype] [smallint] NOT NULL,
	[doctype] [smallint] NOT NULL,
	[orderno] [int] NOT NULL,
	[orderdate] [smalldatetime] NOT NULL,
	[itemtype] [smallint] NOT NULL,
	[itemean] [char](13) NOT NULL,
	[barcode] [char](20) NOT NULL,
	[unit] [smallint] NOT NULL,
	[expirydate] [smalldatetime] NOT NULL,
	[transno] [int] NOT NULL,
	[peices] [smallint] NULL,
	[item_qty] [decimal](12, 3) NULL,
	[item_count] [int] NULL,
	[item_cost] [decimal](12, 3) NULL,
	[actual_qty] [decimal](12, 3) NULL,
	[actual_count] [int] NULL,
	[actual_cost] [decimal](12, 3) NULL,
	[costprice] [decimal](12, 3) NULL,
	[remark] [varchar](50) NULL,
	[userid] [int] NULL,
	[transid] [smallint] NULL,
	[transdate] [smalldatetime] NULL,
	[collection] [smallint] NULL,
	[free_qty] [decimal](12, 3) NOT NULL,
	[posting] [smallint] NOT NULL,
	[Order_code] [numeric](38, 0) NULL,
	[Sites] [int] NULL,
	[Itemclass] [smallint] NULL,
	[Itemsection] [smallint] NULL,
	[Itemgroup] [smallint] NULL,
	[Department] [smallint] NULL,
	[Tax_vat_id] [smallint] NULL,
	[Tax_vat_value] [decimal](12, 3) NULL,
	[Tax_add] [smallint] NULL,
	[Tax_add_value] [decimal](12, 3) NULL,
	[Cost_price_ex_tax] [decimal](12, 3) NULL,
	[Entered_from] [smallint] NULL,
	[Entered_type] [smallint] NULL,
	[Entered_time] [datetime] NULL,
	[Onhand_qty] [decimal](18, 3) NULL,
	[Retailprice] [decimal](18, 3) NULL,
	[Wholeprice] [decimal](13, 3) NULL,
	[Bonus_type] [smallint] NULL,
	[Discountype] [smallint] NULL,
	[Discountpercentage] [decimal](12, 3) NULL,
	[Discountvalue] [decimal](12, 3) NULL,
	[Net_cost_price] [decimal](12, 3) NULL,
	[Notes] [varchar](255) NULL,
	[Reasonid] [int] NULL,
	[Pos_id] [smallint] NULL,
	[Temperature_degree] [decimal](12, 0) NULL,
	[Reserved1] [varchar](500) NULL,
	[Reserved2] [varchar](500) NULL,
	[Reserved3] [varchar](500) NULL,
	[Reserved4] [numeric](18, 3) NULL,
	[Reserved5] [numeric](18, 3) NULL,
	[Reserved6] [datetime] NULL,
	[Reserved7] [datetime] NULL,
	[Reserved8] [int] NULL,
	[Reserved9] [int] NULL,
	[Reserved10] [int] NULL,
	[Reserved11] [datetime] NULL,
	[Reserved12] [datetime] NULL,
	[Reserved13] [int] NULL,
	[Reserved14] [int] NULL,
	[Reserved15] [int] NULL,
 CONSTRAINT [stk_order_items_x] PRIMARY KEY NONCLUSTERED 
(
	[company] ASC,
	[sector] ASC,
	[region] ASC,
	[branch] ASC,
	[section] ASC,
	[transtype] ASC,
	[doctype] ASC,
	[orderno] ASC,
	[orderdate] ASC,
	[itemean] ASC,
	[barcode] ASC,
	[expirydate] ASC,
	[transno] ASC)
)
